### ISSUE TITLE
[Bug Report]When I use extension flask-debugtoolbar , error happended.

### ISSUE THREAD

**Issue by shijl0925** [ShangSky/flask-sugar#7]
AssertionError: View function mapping is overwriting an existing endpoint function: debugtoolbar.sql_select

Traceback (most recent call last)
File "/Users/shijl0925/Pycharm/flask-example/backend/app/main.py", line 170, in <module>
app = create_app()
File "/Users/shijl0925/Pycharm/flask-example/backend/app/main.py", line 144, in create_app
register_extensions(app_)
File "/Users/shijl0925/Pycharm/flask-example/backend/app/main.py", line 88, in register_extensions
extension.init_app(app)
File "/Users/shijl0925/Pycharm/flask-example/backend/venv/lib/python3.7/site-packages/flask_debugtoolbar/__init__.py", line 84, in init_app
app.register_blueprint(module, url_prefix='/_debug_toolbar/views')
File "/Users/shijl0925/Pycharm/flask-example/backend/venv/lib/python3.7/site-packages/flask/scaffold.py", line 57, in wrapper_func
return f(self, *args, **kwargs)
File "/Users/shijl0925/Pycharm/flask-example/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1028, in register_blueprint
blueprint.register(self, options)
File "/Users/shijl0925/Pycharm/flask-example/backend/venv/lib/python3.7/site-packages/flask/blueprints.py", line 370, in register
deferred(state)
File "/Users/shijl0925/Pycharm/flask-example/backend/venv/lib/python3.7/site-packages/flask/blueprints.py", line 426, in <lambda>
**options,
File "/Users/shijl0925/Pycharm/flask-example/backend/venv/lib/python3.7/site-packages/flask/blueprints.py", line 108, in add_url_rule
**options,
File "/Users/shijl0925/Pycharm/flask-example/backend/venv/lib/python3.7/site-packages/flask_sugar/app.py", line 143, in add_url_rule
super().add_url_rule(rule, endpoint, view, provide_automatic_options, **options)
File "/Users/shijl0925/Pycharm/flask-example/backend/venv/lib/python3.7/site-packages/flask/scaffold.py", line 57, in wrapper_func
return f(self, *args, **kwargs)
File "/Users/shijl0925/Pycharm/flask-example/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1091, in add_url_rule
"View function mapping is overwriting an existing"
AssertionError: View function mapping is overwriting an existing endpoint function: debugtoolbar.sql_select

**Comment by ShangSky** [comment]
In version 0.0.14 I solved this problem
