### ISSUE TITLE
[Bug Report]When I use extension flask-admin , error happended.

### ISSUE THREAD

**Issue by shijl0925** [ShangSky/flask-sugar#8]
flask 2.0.2
flask-admin 1.6.0
flask-sugar 0.0.14

127.0.0.1 - - [08/Feb/2022 10:46:51] "GET /apis/openapi.json HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/shijl0925/Pycharm/flask-example/backend/venv/lib/python3.7/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/shijl0925/Pycharm/flask-example/backend/venv/lib/python3.7/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/shijl0925/Pycharm/flask-example/backend/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/shijl0925/Pycharm/flask-example/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/shijl0925/Pycharm/flask-example/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/shijl0925/Pycharm/flask-example/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/shijl0925/Pycharm/flask-example/backend/venv/lib/python3.7/site-packages/flask_sugar/view.py", line 312, in __call__
    response = self.view_func(**cleaned_data)
  File "/Users/shijl0925/Pycharm/flask-example/backend/venv/lib/python3.7/site-packages/flask_sugar/openapi.py", line 77, in openapi_json_view
    paths, components = collect_paths_components()
  File "/Users/shijl0925/Pycharm/flask-example/backend/venv/lib/python3.7/site-packages/flask_sugar/openapi.py", line 198, in collect_paths_components
    flat_models, model_name_map=model_name_map, ref_prefix=REF_PREFIX
  File "/Users/shijl0925/Pycharm/flask-example/backend/venv/lib/python3.7/site-packages/flask_sugar/openapi.py", line 185, in schema
    model_name = model_name_map[model]
KeyError: <class 'pydantic.main.flask_admin__model__base__export__ParamModel'>

**Comment by ShangSky** [comment]
show your code

**Comment by shijl0925** [comment]
https://github.com/shijl0925/flask-boilerplate/tree/sugar
**branch: sugar**

**Comment by shijl0925** [comment]
[flask-boilerplate-sugar.zip](https://github.com/ShangSky/flask-sugar/files/8029097/flask-boilerplate-sugar.zip)

**Comment by ShangSky** [comment]
> [flask-boilerplate-sugar.zip](https://github.com/ShangSky/flask-sugar/files/8029097/flask-boilerplate-sugar.zip)

Please give me a minimal code to reproduce the problem

**Comment by shijl0925** [comment]
code
```
import os
from datetime import datetime
from flask_sugar import Sugar as FlaskAPI
from flask_sqlalchemy import SQLAlchemy
from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView

basedir = os.path.abspath(os.path.dirname(__file__))


admin = Admin(name='Admin', template_mode='bootstrap4')
db = SQLAlchemy()


class Settings(db.Model):
    __tablename__ = "settings"

    id = db.Column(db.Integer, primary_key=True)

    name = db.Column(db.String(64), unique=True)
    value = db.Column(db.String(128), nullable=True)
    description = db.Column(db.String(64), nullable=True)


class Request(db.Model):
    __tablename__ = "request"

    id = db.Column(db.Integer, primary_key=True)

    method = db.Column(db.String(8))
    module = db.Column(db.String(64))

    full_path = db.Column(db.String(256))
    ip = db.Column(db.String(64))
    timestamp = db.Column(db.DateTime(), default=datetime.now)
    user_agent = db.Column(db.Text)

    status_code = db.Column(db.Integer)
    arguments = db.Column(db.PickleType, default=dict())


class DevelopmentConfig(object):
    SECRET_KEY = b'_5#y2L"F4Q8z\n\xec]flask_app/'
    DEBUG = True
    SQLALCHEMY_DATABASE_URI = 'sqlite:///' + os.path.join(basedir, 'data.sqlite')


def create_app():
    app_ = FlaskAPI(
        __name__,
        openapi_json_url="/apis/openapi.json",
        swagger_url="/apis/swagger",
        redoc_url="/apis/redoc"
    )
    app_.config.from_object(DevelopmentConfig)

    db.init_app(app_)
    admin.init_app(app_)

    admin.add_view(ModelView(Settings, db.session))
    admin.add_view(ModelView(Request, db.session))

    return app_


app = create_app()
```

requirements.txt:
```
SQLAlchemy
Flask-SQLAlchemy>=2.3.2
flask>=2.0.0
Werkzeug>=2.0.0
itsdangerous>=2.0.0
flask-sugar
flask-admin
pydantic
```


[mini.zip](https://github.com/ShangSky/flask-sugar/files/8033692/mini.zip)

**Comment by shijl0925** [comment]
error happen in the code when I register model in the admin extension.
```
admin.add_view(ModelView(Settings, db.session))
admin.add_view(ModelView(Request, db.session))
```

**Comment by ShangSky** [comment]
> 

I used this code and found no errors
<img width="849" alt="image" src="https://user-images.githubusercontent.com/45486831/153326039-bb722c67-e106-4af6-a0a1-883ac8ced77b.png">

**Comment by shijl0925** [comment]
"http://localhost:5000/apis/swagger", "http://localhost:5000/apis/redoc" web pages have error. please check again.

**Comment by ShangSky** [comment]
reason: I found that the function names created dynamically by flask-admin are the same
In version 0.0.15 I solved this problem

**Comment by shijl0925** [comment]
thanks
